### PR TITLE
Better definition of clock domains

### PR DESCRIPTION
**Pull request by galibert**
[Rendered](https://github.com/galibert/amaranth-rfcs/blob/clock-domains/text/0012-better-clock-domains.md)

### CODE REVIEW

**Comment by josuah** [comment]
The new syntax, in particular the new ClockDomain constructor, makes it a whole lot easier to read!

To have an insight on who used the existing API:
https://github.com/search?q=enableinserter+language%3APython&type=code&l=Python

**Comment by whitequark** [comment]
This all is broadly reasonable and in line with what I've been planning already. It is a very large change however, and I think we won't get around to it particularly soon. Ultimately something like this needs to be done before 1.0, and probably this year.

**Comment by jevinskie** [comment]
Has anybody thought about adding clock frequency information to ClockDomains?

I opened https://github.com/enjoy-digital/litex/pull/1310 because I wanted build-time assertions to ensure that a hard IP block wasn’t being overclocked.

Perhaps `freq`, `freq_min`, `freq_max` and maybe a `freq_margin` (for PLL outputs that have guaranteed tolerances) could be useful? Or would that be better served by a new RFC?

**Comment by whitequark** [comment]
> Has anybody thought about adding clock frequency information to ClockDomains?

Yes. This is a rather complex problem in situations where frequency can change at runtime. It should not be a part of this RFC.

**Comment by whitequark** [comment]
Reopened as requested by the author.

**Comment by whitequark** [comment]
I've listed the challenges associated with the current clock domain system in [this conversation](https://libera.irclog.whitequark.org/amaranth-lang/2024-03-01#1709318917-1709327968;). To move this proposal forward, it will have to give an answer to these challenges, especially the interaction of sync reset, async reset, and enable.

More broadly, I think that the domain scoping and the domain control set semantics are topics that can probably be addressed separately. Given how troublesome domain scoping is for both understanding the language and for implementing it (NIR and the platform layer struggle with it) this may be worth addressing separately.

**Comment by galibert** [comment]
That rfc is around a year and half old and has never been discussed.  By now, I'm not close enough to top-of-tree development of amaranth to be able to see whether it still makes sense, and I'm starting to have a feeling its existence is preventing other people to propose things on the topic.  So it's time to close it.

**Pull request closed without merging**
