### PR TITLE
Add RFC for `Choice`.

### PR DESCRIPTION
**Pull request by wanda-phi**
[Rendered](https://github.com/wanda-phi/rfcs/blob/choice/text/0052-choice.md)

### CODE REVIEW

**Comment by whitequark** [comment]
Guard syntax bikeshed:

1. Just stuff it in the list:

```
Choice(foo, {
  (1, guard): bar
})
```

2. Context manager:

```
with Choice(foo) as c:
    with c.Case(1, if=guard):
        c.eq(bar)
```

(I don't love any of these. They're also both backward compatible.)

**Comment by wanda-phi** [comment]
> Guard syntax bikeshed:
> 
>     1. Just stuff it in the list:
> 
> 
> ```
> Choice(foo, {
>   (1, guard): bar
> })
> ```

That won't work (`Value` is not hashable)

**Comment by whitequark** [comment]
In addition, the existing Mux expression is made valid on the left-hand side of an assignment, as if it was lowered as follows:

```py
def Mux(sel, val1, val0):
    return Choice(a).case(1, val1).default(val0)
```

Shouldn't it be the opposite?

```py
def Mux(sel, val1, val0):
    return Choice(a).case(0, val0).default(val1)
```

**Comment by wanda-phi** [comment]
> > In addition, the existing Mux expression is made valid on the left-hand side of an assignment, as if it was lowered as follows:
> > ```python
> > def Mux(sel, val1, val0):
> >     return Choice(a).case(1, val1).default(val0)
> > ```
> 
> Shouldn't it be the opposite?
> 
> ```python
> def Mux(sel, val1, val0):
>     return Choice(a).case(0, val0).default(val1)
> ```

fixed, thanks

**Comment by whitequark** [comment]
We have [discussed](https://libera.irclog.whitequark.org/amaranth-lang/2024-07-01#1719856007-1719856763;) this RFC on the 2024-07-01 weekly meeting. The disposition was to **merge**.

**Comment by whitequark** [comment]
Thanks @wanda-phi for your work!

**Pull request merged**
