### PR TITLE
Add an RFC for `ShapeCastable.from_bits` and `lib.data.Const`.

### PR DESCRIPTION
**Pull request by wanda-phi**
[Rendered](https://github.com/wanda-phi/rfcs/blob/literal/text/0051-from-bits-literalview.md)

### CODE REVIEW

**Comment by whitequark** [comment]
Would `from_bits` ever need to know the size of the original value?

**Comment by wanda-phi** [comment]
> Would `from_bits` ever need to know the size of the original value?

It is called on `ShapeCastable`, which has the length available (since it has to implement `as_shape()`).

**Comment by whitequark** [comment]
We have [discussed](https://libera.irclog.whitequark.org/amaranth-lang/2024-03-04#1709572254-1709574200;) this RFC on the 2024-03-04 weekly meeting. The disposition was to **merge**, with the following changes:
- `lib.data.LiteralView` is renamed to `lib.data.Const` and made immutable;
- `ShapeCastable.from_bits` is allowed to return any type as long as `ShapeCastable.const` can turn it back into a const-castable value;
  - Additional unresolved question: With the *same* bit pattern or *equivalent* bit pattern? This is important if we ever try to roundtrip a NaN through Python's `float`.
- `lib.data.Layout.const` is changed to return a `lib.data.Const`;
- Mentioning that instead of mutating a `lib.data.Const` in simulation, one can set the field directly.

**Comment by whitequark** [comment]
Thank you!

**Pull request merged**
